### ISSUE TITLE
Error when adding package

### ISSUE THREAD

**Issue by OptimisticLock** [VeliovGroup/Meteor-Template-helpers#1]
```
E:\work\aaa\meteor>meteor update
This project is already at Meteor 1.2.0.2, the latest release.
Your top-level dependencies are at their latest compatible versions.

E:\work\aaa\meteor>meteor add ostrio:templatehelpers

C:\Users\I\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32
\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: ENOENT, open 'C:\Users\I\AppData\Local\Temp\mt-lzvxy1\web.browser\ostrio:
templatehelpers.js'
    at Object.Future.wait (C:\Users\I\AppData\Local\.meteor\packages\meteor-tool
\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)

    at C:\tools\fs\files.js:1331:28
    at Object.wrapper [as open] (C:\tools\fs\files.js:1334:20)
    at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:1474:20)

    at C:\tools\isobuild\isopack.js:973:26
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\I\AppData\Local\.meteor\packages\mete
or-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\unders
core.js:79:11)
    at C:\tools\isobuild\isopack.js:971:9
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\I\AppData\Local\.meteor\packages\mete
or-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\unders
core.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopac
k.js:931:7)
    at C:\tools\packaging\tropohouse.js:500:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\I\AppData\Local\.meteor\packages\mete
or-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\unders
core.js:79:11)
    at C:\tools\packaging\tropohouse.js:499:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at Object.download (C:\tools\packaging\tropohouse.js:437:20)
    at C:\tools\packaging\tropohouse.js:575:22
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packagi
ng\tropohouse.js:572:20)
    at C:\tools\project-context.js:702:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at C:\tools\project-context.js:701:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-contex
t.js:700:13)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:
235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:240:10)
    at C:\tools\cli\commands-packages.js:1996:20
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packag
es.js:1995:27)
    at C:\tools\cli\main.js:1378:23
    - - - - -


```

**Comment by dr-dimitru** [comment]
1. Windows? 
2. ~~CoffeeScript is installed? (Try to install separate npm module `npm install -g coffee-script`)~~ (_I forgot this package fully in vanilla js_)
3. Looks like this package was fetched partly the `ENOENT` error, do you tried to run `meteor reset`, then `meteor add ostrio:templatehelpers` again?
4. Also, you could try to:
   1. Go to project's folder `cd my-project`
   2. `mkdir packages`
   3. `cd packages`
   4. `git clone https://github.com/VeliovGroup/Meteor-Template-helpers.git`
   5. `cd ../`
   6. `meteor remove ostrio:templatehelpers`
   7. `meteor reset`
   8. `meteor add ostrio:templatehelpers`
   9. `meteor`

**Comment by dr-dimitru** [comment]
@OptimisticLock is this issue still persists?

**Comment by dr-dimitru** [comment]
Closed due to no response from topic starter
